### ISSUE TITLE
Problem with ی letter when using some fonts!

### ISSUE THREAD

**Issue by a-m-dev** [ElectroGryphon/EGGA#8]
Hi there , 
first of all , i honestly appreciate your passion about unity for creating such a great RTL language support unity package!

so , let's move on ...
the problem is when i using some fonts like "Samim" or "IranSans" neigher some of other fonts , a double dot appears in bottom of "ی"  letter , Like this : 
![untitled-2](https://user-images.githubusercontent.com/29652890/35439223-11cd0f1c-02af-11e8-8e61-acaff1c8e985.png)

how can i remove those double dots ???

**Comment by omid3098** [comment]
Hi these keys "ی" and "ي" have different keycodes:
ی: U+0649
ي: U+064A

I can not remember why did I add these lines:
https://github.com/ElectroGryphon/EGGA/blob/f539fe24aaff16df3131434abd508980343a2e6e/UPersian/Scripts/Utils/UPersianUtils.cs#L18

but the short answer would be to comment this line and check if your problem is fixed.

**Comment by omid3098** [comment]
hmm. this is what I see in my local code.
![image](https://user-images.githubusercontent.com/6388730/35443307-e2530c08-02bf-11e8-8fef-e04a5d67347f.png)

this shows that I am trying to replace ی with ي.
which seems strange.
but the code I linked shows the correct attempt. which should prevent using ي and replace all of them to ی with no dots under.
so commenting that line may not solve any of your problems

**Comment by a-m-dev** [comment]
hold on a sec ...

**Comment by a-m-dev** [comment]
i think problem is unity ...
b/c 
when i type the phrase "مثالی برای حرف ی" in untiy itself via text box it appears with double dots in bottom of the "ی" letter , BUT when i write that phrase in another place (address bar of the chrome) and copy it to unity text box, the "ی" letter appears with no double dots in bottom (ha ha , double dots in bottom , haha) 

try it , tell me what did you get ... i'm waiting for any respond !!!!

**Comment by a-m-dev** [comment]
ohhhhhhhhhh 
one specific circumstance for that to happen!
it happens when only you just comment the same code that you said earlier 
but another problem raises with "ل"  letter 
try it , you will see that the "ل"  letter does not snap to the "ی" letter in phrase "مثالی"!!!!
little bit strange !!!!

**Comment by Enzx** [comment]
I think the problem comes from ArabicFix plugin...
In Arabic Unicode, there are presentation form characters like 'ﱄ' (U+FC44) and 'ﱃ' (U+FC43) that combines two characters into one... 
Change ArabicFix with [NBidi](with https://sourceforge.net/projects/nbidi/), which is a standard implementation of [Unicode bidirectional algorithm](http://www.unicode.org/reports/tr9/ )... 
If this fixes the problem we'll change the algorithm too. 
I didn't have that snapping problem can you tell me the reproduce steps?

**Comment by omid3098** [comment]
there is no problem with ل its ی that can not connect to the ل.
I guess this was the reason that I added that line. sorry for no comment in my code while I cant remember its usage!
you can try that with مثاکی or مثاسی and check that ی would not attach to previous character.

**Comment by omid3098** [comment]
@Enzx if you already checked NBidi, and it worked, we can use that one.
however there is an updated version for ArabicFix plugin which we did not used in our latest version.

https://github.com/Konash/arabic-support-unity

**Comment by omid3098** [comment]
The problem was because of wrong character key code. I replaced the ي with the correct ى and now the problem is fixed.

**Comment by a-m-dev** [comment]
```
while (true)
    thankYou++;
```

![untitled-1](https://user-images.githubusercontent.com/29652890/39203388-dc40b25e-4809-11e8-8c94-8510eacea299.png)
